### ISSUE TITLE
error whe trying to enable or disable url blocklist

### ISSUE THREAD

**Issue by manolixgt** [frenck/python-adguardhome#233]
im having this issue when i try to enable url e.g. urllist = "https://raw.githubusercontent.com/user/repository/main/blocklists.txt"

File "C:\Users\Tahuite\AppData\Local\Programs\Python\Python38-32\lib\site-packages\adguardhome\filtering.py", line 97, in enable_url
    raise AdGuardHomeError(
adguardhome.exceptions.AdGuardHomeError: ('Failed enabling URL on AdGuard Home filter', AdGuardHomeError(400, {'message': 'invalid URL or file path\n'})) 

need to provide an especific format? or need to remove something? thanks

**Comment by frenck** [comment]
Fixed in v0.5.0
