### ISSUE TITLE
Exception Handling and User Feedback

### ISSUE THREAD

**Issue by hl2guide** [frenck/python-adguardhome#270]
Please improve the Exception handling in the code to help the user do troubelshooting.

Please also consider actual documenation for this package.

e.g.:

![image](https://user-images.githubusercontent.com/17044982/112604310-17afb200-8e6a-11eb-8ac0-d4cf30306247.png)

My code:

```
from adguardhome import AdGuardHome

import asyncio

ipAddress = "192.168.1.100"

async def main():
    """Show example how to get status of your AdGuard Home instance."""
    async with AdGuardHome(ipAddress) as adguard:
        version = await adguard.version()
        print("AdGuard version:", version)

        active = await adguard.protection_enabled()
        active = "Yes" if active else "No"
        print("Protection enabled?", active)

        if not active:
            print("AdGuard Home protection disabled. Enabling...")
            await adguard.enable_protection()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by frenck** [comment]
The code throws an exception so the user can handle it as they see fit. All exceptions and methods provided are documented in code.

Feel free to contribute if you think things can be improved, with the current issue, I can't do anything.
