### ISSUE TITLE
Please add examples

### ISSUE THREAD

**Issue by badboiaustria** [frenck/python-adguardhome#686]
Hi!
For me it is difficult to use it for retrieving the querylog and to alter the filtering.
Would you be so kind to add examples how to retrieve the logs and how to change items in custom filter?

That would be nice
Michael

**Comment by frenck** [comment]
Python examples can be found in the examples folder:

https://github.com/frenck/python-adguardhome/tree/main/examples

There are control examples in there as well. Maybe not directly for the specific you mentioned above. However, those examples would almost be exactly the same (except for a different method with, e.g., a parameter).

../Frenck
